CREATE TABLE ccl (
CAND_ID VARCHAR2(9) NOT NULL, 
CAND_ELECTION_YR INT NOT NULL,
FEC_ELECTION_YR INT NOT NULL, 
CMTE_ID VARCHAR2(9), 
CMTE_TP VARCHAR2(1),
CMTE_DSGN VARCHAR2(1),
LINKAGE_ID INT NOT NULL
);