CREATE TABLE com_master (
CMTE_ID VARCHAR(9) NOT NULL, 
CMTE_NM VARCHAR(200), 
TRES_NM VARCHAR(90), 
CMTE_ST1 VARCHAR(34), 
CMTE_ST2 VARCHAR(34),
CMTE_CITY VARCHAR(30), 
CMTE_ST VARCHAR(2),
CMTE_ZIP VARCHAR(9),
CMTE_DSGN VARCHAR(21),
CMTE_TP VARCHAR(1), 
CMTE_PTY_AFFILIATION VARCHAR(3), 
CMTE_FILING_FREQ VARCHAR(1), 
ORG_TP VARCHAR(1), 
CONNECTED_ORG_NM VARCHAR(200), 
CAND_ID VARCHAR(9)
);