DROP TABLE indep_expend;
CREATE TABLE indep_expend (
Index INT,	
CMTE_ID VARCHAR (15), 
AMNDT_IND VARCHAR (1),
RPT_TP VARCHAR (4),
TRANSACTION_PGI VARCHAR (6),
IMAGE_NUM TEXT, 
TRANSACTION_TP VARCHAR (4),
ENTITY_TP VARCHAR (4),
NAME TEXT,
CITY VARCHAR (40),
STATE VARCHAR (3),
ZIP_CODE VARCHAR (15),
EMPLOYER VARCHAR (20),
OCCUPATION VARCHAR (20),
TRANSACTION_DT DATE,
TRANSACTION_AMT INT, 
OTHER_ID VARCHAR (20),
CAND_ID VARCHAR (20),
TRAN_ID TEXT,
FILE_NUM INT,
MEMO_CD VARCHAR (2),
MEMO_TEXT TEXT,
SUB_ID TEXT);

CREATE TABLE CAND_MASTER (
CAND_ID VARCHAR(9) NOT NULL, 
CAND_NAME VARCHAR(200),
CAND_PTY_AFFILIATION VARCHAR(3), 
CAND_ELECTION_YR INT, 
CAND_OFFICE_ST VARCHAR(2), 
CAND_OFFICE VARCHAR(1), 
CAND_OFFICE_DISTRICT VARCHAR(2), 
CAND_ICI VARCHAR(1), 
CAND_STATUS VARCHAR(1), 
CAND_PCC VARCHAR(9), 
CAND_ST1 VARCHAR(34), 
CAND_ST2 VARCHAR(34), 
CAND_CITY VARCHAR(30), 
CAND_ST VARCHAR(2), 
CAND_ZIP VARCHAR(9)
);

CREATE TABLE com_master (
CMTE_ID VARCHAR(9) NOT NULL, 
CMTE_NM VARCHAR(200), 
TRES_NM VARCHAR(90), 
CMTE_ST1 VARCHAR(34), 
CMTE_ST2 VARCHAR(34),
CMTE_CITY VARCHAR(30), 
CMTE_ST VARCHAR(2),
CMTE_ZIP VARCHAR(9),
CMTE_DSGN VARCHAR(21),
CMTE_TP VARCHAR(1), 
CMTE_PTY_AFFILIATION VARCHAR(3), 
CMTE_FILING_FREQ VARCHAR(1), 
ORG_TP VARCHAR(1), 
CONNECTED_ORG_NM VARCHAR(200), 
CAND_ID VARCHAR(9)
);

CREATE TABLE ccl (
CAND_ID VARCHAR(9) NOT NULL, 
CAND_ELECTION_YR INT NOT NULL,
FEC_ELECTION_YR INT NOT NULL, 
CMTE_ID VARCHAR(9), 
CMTE_TP VARCHAR(1),
CMTE_DSGN VARCHAR(1),
LINKAGE_ID INT NOT NULL
);

SELECT cand_master.* ::text, count(*)
FROM cand_master
GROUP BY cand_master.*
HAVING count(*) > 1;

DELETE FROM cand_master WHERE cand_name = 'PARKS, JUAN';
INSERT INTO cand_master (CAND_ID, CAND_NAME, CAND_PTY_AFFILIATION, 
			CAND_ELECTION_YR, CAND_OFFICE_ST, CAND_OFFICE,
			CAND_OFFICE_DISTRICT, CAND_ICI, CAND_STATUS,
			CAND_PCC, CAND_ST1,CAND_CITY, CAND_ST, 
			CAND_ZIP)
VALUES ('H8GA04117','PARKS, JUAN','DEM',
	'2018','GA','H','4','C','P',
	'C00654699','6067 FAIRINGTON FARMS LANE',
	'LITHONIA','GA','30038');
	
DELETE FROM com_master WHERE CMTE_ID = 'C00654699';
DELETE FROM com_master WHERE CMTE_ID = 'C00690123';

INSERT INTO com_master(CMTE_ID,CMTE_NM, TRES_NM, CMTE_ST1, 
			CMTE_CITY, 
			CMTE_ST, CMTE_ZIP, 
			CMTE_DSGN, CMTE_TP, 
			CMTE_PTY_AFFILIATION, CMTE_FILING_FREQ, 
			CAND_ID)
VALUES ('C00654699','THE COMMITTEE TO ELECT JUAN PARKS', 
	'MCMILLAN, EVA MRS', '6067 FAIRINGTON FARMS LANE',
	'LITHONIA','GA',
	'300381547','P',
	'H','DEM',
	'A', 'H8GA04117'
);

SELECT com_master.* ::text, count(*)
FROM com_master
GROUP BY com_master.*
HAVING count(*) > 1;

INSERT INTO com_master(CMTE_ID,CMTE_NM, TRES_NM, CMTE_ST1, 
			CMTE_CITY, 
			CMTE_ST, CMTE_ZIP, 
			CMTE_DSGN, CMTE_TP, 
			CMTE_FILING_FREQ, 
			CAND_ID)
VALUES ('C00690123','INDEPENDENT VOICES OF CHANGE',
	'PHELAN, JOHN','2 MEGHANS WAY',
	'LYNN','MA','1904','U','O','T','H8NJ07256');

ALTER TABLE CAND_MASTER ADD PRIMARY KEY (CAND_ID);
ALTER TABLE com_master ADD PRIMARY KEY (CMTE_ID);
ALTER TABLE ccl ADD PRIMARY KEY (LINKAGE_ID);
ALTER TABLE indep_expend ADD PRIMARY KEY (INDEX);

